-- 20260725172736_harden_security_definer_helpers
--
-- ALREADY APPLIED to Supabase project ccxatzfsvzetciiwsjlj as version 20260725172736.
-- This file intentionally contains no DDL: it exists so the repository's
-- migration history matches production, which is what the Supabase GitHub
-- check compares. Running it is a no-op; the schema it describes is live.
--
-- The authoritative statement text is recorded on the project itself:
--   select array_to_string(statements, '') from supabase_migrations.schema_migrations
--   where version = '20260725172736';
--   -- md5 496344190057bdc7e55e9493afad3010, 2118 bytes
--
-- To restore the full text here, run the query above and replace this file's
-- contents verbatim (the md5 must match). Do not write new DDL under this
-- version number.
